### ISSUE TITLE
Color trigger format not what muddler expects

### ISSUE THREAD

**Issue by demonnic** [Edru2/DeMuddler#5]
Was helping someone troubleshoot a demuddled package this evening and discovered that the color triggers are having their patterns written out as, for example, "FG8BG2" but muddler expects it as "8,2"

As it stands currently this causes muddler to fail while parsing those triggers as it splits on the `,` and attempts to read index 0 and 1 for the fg and bg respectively, but index 1 is out of bounds when you split `FG8BG2` on `,`

I'm considering adding support for the second style to muddler but decided I should file an issue on it either way in the meantime.

**Comment by Edru2** [comment]
:thinking: 
Was about to work on this and noticed that Mudlet xml seems to work differently then I expected.
FG4BG0 seems to be ANSI 1 and Default which then seems to be converted to ANSI_COLORS_F{4}_B{0} in muddler.

So it changes from ANSI 1 (red) to ANSI 4 (blue) and the background from default to black.

Need to check why it is FG4 and not FG1

**Comment by Edru2** [comment]
I'll look at it again as it was just quick and dirty but the last commit should fix the issue :)
