### ISSUE TITLE
Reorder the json 

### ISSUE THREAD

**Issue by hungrybeagle** [Edru2/DeMuddler#7]
Triggers are demuddled and the json puts the name at the top of the trigger;  However, for keys, aliases, scripts and timers, the name is  not at the top of the list.  Placing it at the top would make it easier to find the correct block of code.

Sample trigger demuddle
```
              "name": "lowSP",
              "isActive": "yes",
              "isFolder": "no",
              "multiline": "no",
              "multilineDelta": "0",
              "matchall": "no",
```

Sample alias demuddle
```
       {
              "isActive": "yes",
              "isFolder": "no",
              "name": "aaCheckStatus",
              "regex": "^aa$",
              "script": ""
       },
```

**Comment by Edru2** [comment]
this should be fixed now
