### ISSUE TITLE
Lua code on script folders not included

### ISSUE THREAD

**Issue by mpconley** [Edru2/DeMuddler#9]
Processed the StickMUD UI through DeMuddler and found the code on the script folders was not included.

Here is a sample of where that code lived.
<img width="632" alt="Screenshot 2024-06-30 at 11 09 27 AM" src="https://github.com/Edru2/DeMuddler/assets/3058178/193e53de-db53-4f12-8127-cb59245a1827">

Nice job on DeMuddler!

-Tamarindo@StickMUD

**Comment by Edru2** [comment]
This should be fixed now in the latest release.
